INSERT INTO ENCOMENDERO (IDPERSONA, NOMBRES,  APELLIDOS, CEDULA, FNACIMIENTO, CELULAR) VALUES (1, 'Christian Manuel', 'Chunga Bayas', '0941106445', '1998-08-04', '0941106445')
INSERT INTO ENCOMENDERO (IDPERSONA, NOMBRES,  APELLIDOS, CEDULA, FNACIMIENTO, CELULAR) VALUES (2, 'Paola Alexandra', 'Zambrano De La Cruz', '1751288505', '1998-08-17', '0000000000')
INSERT INTO ENCOMENDERO (IDPERSONA, NOMBRES,  APELLIDOS, CEDULA, FNACIMIENTO, CELULAR) VALUES (3, 'Juan Alexis', 'Regato Rosero', '0999999999', '1998-01-01', '0000000000')

INSERT INTO CLIENTE (IDPERSONA, NOMBRES,  APELLIDOS, CORREO, FNACIMIENTO, FREGISTRO, CELULAR, IDUSUARIO) VALUES (1, 'Christian Manuel', 'Chunga Bayas', 'cmchunga@espe.edu.ec', '1998-08-04', '1998-08-04', '0941106445',1)
INSERT INTO CLIENTE (IDPERSONA, NOMBRES,  APELLIDOS, CORREO, FNACIMIENTO, FREGISTRO, CELULAR, IDUSUARIO) VALUES (2, 'Paola Alexandra', 'Zambrano De La Cruz', 'pazambrano@espe.edu.ec', '1998-08-17', '1998-08-17', '0000000000', 2)

INSERT INTO RESTAURANTE (IDRESTAURANTE, NOMBRE,  CELULAR, CORREO, DIRECCION, TIPO, WEB) VALUES (1, 'El Foraneo Feliz', '0983187623', 'pao.zambranoo_@hotmail.com', 'Latacunga', 'Comida rapida', 'www.foraneofeliz.com')
INSERT INTO RESTAURANTE (IDRESTAURANTE, NOMBRE,  CELULAR, CORREO, DIRECCION, TIPO, WEB) VALUES (2, 'Pio Pio', '0999999999', 'pio_pio@outlook.es', 'Av. Unidad Nacional', 'Comida rapida', 'www.piopio.com')
INSERT INTO RESTAURANTE (IDRESTAURANTE, NOMBRE,  CELULAR, CORREO, DIRECCION, TIPO, WEB) VALUES (3, 'Food Station', '0999999999', 'foodstation@outlook.es', 'Av. Unidad Nacional', 'Comida rapida', 'www.foodstation.com')

INSERT INTO PLATILLO (IDPLATILLO, NOMBRE,  DESCRIPCION, PRECIO, IDRESTAURANTE) VALUES (1, 'Cordon bleu', 'Pollo relleno con jamon y queso maduro', 5.50, 1)
INSERT INTO PLATILLO (IDPLATILLO, NOMBRE,  DESCRIPCION, PRECIO, IDRESTAURANTE) VALUES (2, 'Pollo a las finas hierbas', 'Pollo al horno con variedad de hierbas', 4.75, 2)

INSERT INTO USUARIO(IDUSUARIO,NOMBRE,CONTRASENIA,HABILITADO,CREADOEN)VALUES(1,'admin','$2a$10$5WUVJTaTvk9GfLA.q7pYLOavF4.Ss4PKbL4DcLUmSfUxMjMJ6/ljG',true,'2019-12-23 15:00:00');
INSERT INTO USUARIO(IDUSUARIO,NOMBRE,CONTRASENIA,HABILITADO,CREADOEN)VALUES(2,'rest','$2a$10$5WUVJTaTvk9GfLA.q7pYLOavF4.Ss4PKbL4DcLUmSfUxMjMJ6/ljG',true,'2019-12-23 15:00:00');

INSERT INTO ROL(IDROL,NOMBRE,IDUSUARIO) VALUES(1,'ROLE_ADMIN',1);
INSERT INTO ROL(IDROL,NOMBRE,IDUSUARIO) VALUES(2,'ROLE_RESTAURANTE',2);